
jobs:
  include:
    - stage: Merge
      script:
        - wget https://raw.githubusercontent.com/louiscklaw/travis-playlist/master/travis-build-merger/merge_if_success.sh
        - bash merge_if_success.sh | tee merge.log

    - stage: Deploy
      name: deploy to firebase
      script:
        - hostname

import:
  - credentials.yml
