
language: node_js
node_js:
  - 8

cache:
  npm: true

import:
  - credentials.yml
  - .travis-merger.yml
  - firebase_credentials.yml

jobs:
  include:
    - stage: Deploy
      name: deploy to firebase
      install:
        - curl -sL https://firebase.tools | bash
      script:
        - cd firebase-hosting-tryout
        - ./build.sh
        - cd ..

        - cd firebase-functions-tryout
        - ./build.sh
        - cd ..
